name: Action Demo
run-name: ${{ github.actor }} is testing stuff
on: [push]
jobs:
  Explore:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }}"
      - run: echo "Running on ${{ runner.os }}"
      - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}"
      - name: Checkout repo code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner"
      - run: echo "The workflow is now ready to test code"
      - name: List files in repo
        run: |
          ls ${{ github.workspace }}
      - run: echo "The job's status is ${{ job.status }}"
      - run: echo "The associated group is ${{ vars.GROUP }}"
      - run: echo "An unset var ${{ vars.NONE }}"